services:
  postgres:
    image: postgres:latest
    env_file:
      - "./.env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet

networks:
  appnet:
    driver: bridge


volumes:
  postgres_data:

